### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 0x0L** [0x0L/pgeon#10]
- [ ] Window build
- [ ] Fix wheels
      * macosx min platform
      * manylinux platform tag on linux without auditwheel
      * make pgeon a proper python package instead of two modules (pgeon and _pgeon)
- [ ] Add a simple C++ cli tool to have a simpler debug workflow
- [ ] User options need to be actually defined/used in C++ and exposed in cython
- [ ] Add fetch interface & batch interface

**Comment by 0x0L** [comment]
1. ATM the linux build is tagged "linux_x86_64" which would prevent upload to pypi if I understand that correctly. I guess we just need to manually override the platform in setup.py for linux

2. pgeon is not a package per se (no __init__.py) it's just two modules pgeon.py and _pgeon.cpython.so. Probably just a matter of renaming pgeon.py to __init__.py and adding the proper relevant info in setup.py

**Comment by rdbisme** [comment]
About ignoring libraries in auditwheel: https://github.com/pypa/auditwheel/issues/76

**Comment by 0x0L** [comment]
https://github.com/pypa/auditwheel/issues/76#issuecomment-330033780
Not linking at all seems even better

**Comment by rdbisme** [comment]
https://github.com/0x0L/pgeon/pull/14

This creates the manylinux without integrating pyarrow into it. Looks cleaner to me then not linking... We get all the niceties about reading the `.so` dependencies and so on.
